"use client";
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";

// Convex
import { ConvexProvider } from "convex/react";
import { convex } from "@/lib/convex";
import { NamespaceProvider } from "@/components/NamespaceContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NamespaceProvider>
          <ConvexProvider client={convex}>
            <SidebarProvider>
              <AppSidebar />
              <SidebarTrigger />
              {children}
            </SidebarProvider>
          </ConvexProvider>
        </NamespaceProvider>
      </body>
    </html>
  );
}
